# Generated by Django 5.0.7 on 2025-10-11 20:10

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='نام شهر')),
            ],
            options={
                'verbose_name': 'شهر',
                'verbose_name_plural': 'شهرها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='نام استان')),
            ],
            options={
                'verbose_name': 'استان',
                'verbose_name_plural': 'استان\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('customer', 'مشتری'), ('business', 'کسب\u200cوکار'), ('admin', 'مدیر'), ('it_manager', 'مدیر فنی سایت'), ('project_manager', 'مدیر پروژه'), ('supporter', 'پشتیبان'), ('customer', 'مشتری'), ('financial_manager', 'مدیر مالی')], max_length=20)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='user_images/')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('first_name', models.CharField(blank=True, max_length=150, null=True)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام کسب\u200cوکار')),
                ('business_phone', models.CharField(blank=True, max_length=11, null=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='آدرس')),
                ('rating_avg', models.FloatField(default=0)),
                ('business_location_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('business_location_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='business_logos/', verbose_name='لوگو')),
                ('instagram_link', models.URLField(blank=True, null=True, verbose_name='لینک صفحه اینستاگرام')),
                ('website_link', models.URLField(blank=True, null=True, verbose_name='لینک سایت')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'business'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.city')),
            ],
            options={
                'verbose_name': 'پروفایل کسب\u200cوکار',
                'verbose_name_plural': 'پروفایل\u200c کسب\u200cوکارها',
            },
        ),
        migrations.CreateModel(
            name='BusinessGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='business_gallery_images/', verbose_name='تصویر')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان تصویر')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات تصویر')),
                ('is_featured', models.BooleanField(default=False, verbose_name='تصویر شاخص')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='accounts.businessprofile', verbose_name='پروفایل کسب\u200cوکار')),
            ],
            options={
                'verbose_name': 'تصویر گالری کسب\u200cوکار',
                'verbose_name_plural': 'تصاویر گالری کسب\u200cوکار',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[('male', 'مرد'), ('female', 'زن')], max_length=10, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('membership_level', models.CharField(choices=[('bronze', 'برنزی'), ('silver', 'نقره\u200cای'), ('vip', 'ویژه')], default='bronze', max_length=10)),
                ('points', models.IntegerField(default=0)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.city')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'customer'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پروفایل مشتری',
                'verbose_name_plural': 'پروفایل\u200c مشتریان',
            },
        ),
        migrations.CreateModel(
            name='FinancialManagerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_financial_manager', models.BooleanField(default=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'financial_manager'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پروفایل مدیر مالی',
                'verbose_name_plural': 'پروفایل\u200c مدیران مالی',
            },
        ),
        migrations.CreateModel(
            name='ITManagerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_staff', models.BooleanField(default=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'it_manager'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پروفایل مدیر فنی سایت',
                'verbose_name_plural': 'پروفایل\u200c مدیران فنی سایت',
            },
        ),
        migrations.CreateModel(
            name='ProjectManagerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_manager', models.BooleanField(default=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'project_manager'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پروفایل مدیر پروژه',
                'verbose_name_plural': 'پروفایل\u200c مدیران پروژه',
            },
        ),
        migrations.AddField(
            model_name='city',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='accounts.province', verbose_name='استان'),
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='accounts.servicecategory')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی خدمات',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای خدمات',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.servicecategory', verbose_name='دسته\u200cبندی'),
        ),
        migrations.CreateModel(
            name='SupporterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_supporter', models.BooleanField(default=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'supporter'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پروفایل پشتیبان',
                'verbose_name_plural': 'پروفایل\u200c پشتیبانان',
            },
        ),
        migrations.CreateModel(
            name='BusinessWorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('weekday', models.IntegerField(choices=[(0, 'شنبه'), (1, 'یکشنبه'), (2, 'دوشنبه'), (3, 'سه\u200cشنبه'), (4, 'چهارشنبه'), (5, 'پنج\u200cشنبه'), (6, 'جمعه')], verbose_name='روز هفته')),
                ('start_time', models.TimeField(verbose_name='ساعت شروع')),
                ('end_time', models.TimeField(verbose_name='ساعت پایان')),
                ('is_closed', models.BooleanField(default=False, verbose_name='تعطیل')),
                ('is_break', models.BooleanField(default=False, verbose_name='استراحت/تعطیلی میانی')),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='accounts.businessprofile', verbose_name='پروفایل کسب\u200cوکار')),
            ],
            options={
                'verbose_name': 'ساعت کاری کسب\u200cوکار',
                'verbose_name_plural': 'ساعات کاری کسب\u200cوکار',
                'ordering': ['weekday', 'start_time'],
                'unique_together': {('business_profile', 'weekday', 'start_time')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('name', 'province')},
        ),
    ]
