# Generated by Django 5.0.7 on 2025-11-02 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='unique_code',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='کد منحصر به فرد'),
        ),
    ]
