# Generated by Django 5.0.7 on 2025-08-29 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('business', 'Business')], default='customer', max_length=20, verbose_name='نوع کاربر'),
        ),
    ]
