# Generated by Django 5.0.7 on 2025-08-29 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_userprofile_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='business_type',
            field=models.CharField(blank=True, choices=[('natural', 'حقیقی'), ('legal', 'حقوقی')], max_length=10, null=True, verbose_name='نوع کسب\u200cوکار'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='نام شرکت'),
        ),
    ]
