# Generated by Django 5.0.7 on 2025-11-09 21:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_businessprofile_unique_code'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveIntegerField()),
                ('text', models.TextField(blank=True, null=True)),
                ('score', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='accounts.customerprofile')),
            ],
            options={
                'verbose_name': 'کامنت',
                'verbose_name_plural': 'کامنت\u200cها',
                'ordering': ['-created_at'],
                'unique_together': {('content_type', 'object_id', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('pending', 'درحال بررسی'), ('approved', 'تایید شده'), ('rejected', 'نیاز به ویرایش'), ('canceled', 'لغو شده'), ('expired', 'منقضی شده')], default='draft', max_length=10)),
                ('is_complete', models.BooleanField(default=False)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='accounts.businessprofile')),
            ],
            options={
                'verbose_name': 'پکیج',
                'verbose_name_plural': 'پکیج\u200cها',
            },
        ),
        migrations.CreateModel(
            name='EliteGift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('count', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('gift', models.CharField(max_length=255)),
                ('score', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('package', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='elite_gift', to='packages.package')),
            ],
            options={
                'verbose_name': 'هدیه ویژه',
                'verbose_name_plural': 'هدایای ویژه',
            },
        ),
        migrations.CreateModel(
            name='DiscountAll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('score', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('package', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discount_all', to='packages.package')),
            ],
            options={
                'verbose_name': 'تخفیف روی تمام محصولات',
                'verbose_name_plural': 'تخفیف\u200cهای روی تمام محصولات',
            },
        ),
        migrations.CreateModel(
            name='SpecificDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('score', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('package', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='specific_discount', to='packages.package')),
            ],
            options={
                'verbose_name': 'تخفیف برای موارد خاص',
                'verbose_name_plural': 'تخفیف\u200cهای برای موارد خاص',
            },
        ),
        migrations.CreateModel(
            name='VipExperienceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('vip_type', models.CharField(choices=[('VIP', 'VIP'), ('VIP+', 'VIP+')], max_length=5)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='accounts.servicecategory')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی VIP',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای VIP',
            },
        ),
        migrations.CreateModel(
            name='VipExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('score', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='packages.package')),
                ('vip_experience_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.vipexperiencecategory')),
            ],
            options={
                'verbose_name': 'انتخاب VIP',
                'verbose_name_plural': 'انتخاب\u200cهای VIP',
            },
        ),
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='packages.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_likes', to='accounts.customerprofile')),
            ],
            options={
                'verbose_name': 'لایک کامنت',
                'verbose_name_plural': 'لایک\u200cهای کامنت',
                'unique_together': {('comment', 'user')},
            },
        ),
    ]
