# Generated by Django 5.0.7 on 2025-11-10 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='service_type',
            field=models.CharField(blank=True, choices=[('discount_all', 'تخفیف روی همه'), ('specific_discount', 'تخفیف خاص'), ('elite_gift', 'هدیه ویژه'), ('vip_experience', 'تجربه VIP')], max_length=50, null=True, verbose_name='نوع سرویس'),
        ),
    ]
