# Generated by Django 5.0.7 on 2025-11-07 20:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_businessprofile_unique_code'),
        ('packages', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerLoyalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('points', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='امتیاز')),
                ('elite_gift_target_reached', models.BooleanField(default=False, verbose_name='به تارگت هدیه الیت رسیده')),
                ('elite_gift_used', models.BooleanField(default=False, verbose_name='هدیه الیت استفاده شده')),
                ('elite_gift_used_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ استفاده از هدیه الیت')),
                ('vip_status', models.CharField(choices=[('none', 'بدون وضعیت VIP'), ('vip', 'VIP'), ('vip_plus', 'VIP+')], default='none', max_length=10, verbose_name='وضعیت VIP')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_loyalties', to='accounts.businessprofile', verbose_name='کسب\u200cوکار')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalties', to='accounts.customerprofile', verbose_name='مشتری')),
            ],
            options={
                'verbose_name': 'وفاداری مشتری',
                'verbose_name_plural': 'وفاداری مشتریان',
                'ordering': ['-points'],
                'unique_together': {('customer', 'business')},
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('original_amount', models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='مبلغ اصلی')),
                ('discount_all_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='مبلغ تخفیف اصلی')),
                ('has_special_discount', models.BooleanField(default=False, verbose_name='دارای تخفیف خاص')),
                ('special_discount_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان تخفیف خاص')),
                ('special_discount_original_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='مبلغ اصلی محصول با تخفیف خاص')),
                ('special_discount_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='مبلغ تخفیف خاص')),
                ('final_amount', models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='مبلغ نهایی')),
                ('points_earned', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='امتیاز کسب شده')),
                ('status', models.CharField(choices=[('pending', 'در انتظار تایید'), ('approved', 'تایید شده'), ('rejected', 'رد شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('note', models.TextField(blank=True, null=True, verbose_name='یادداشت')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.businessprofile', verbose_name='کسب\u200cوکار')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.customerprofile', verbose_name='مشتری')),
                ('loyalty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='loyalty.customerloyalty', verbose_name='وفاداری')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='packages.package', verbose_name='پکیج')),
            ],
            options={
                'verbose_name': 'تراکنش',
                'verbose_name_plural': 'تراکنش\u200cها',
                'ordering': ['-created_at'],
            },
        ),
    ]
