# Generated by Django 5.0.7 on 2025-11-09 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_businessprofile_unique_code'),
        ('loyalty', '0003_transaction_comment_fields'),
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EliteGiftClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('progress_at_claim', models.JSONField(default=dict, verbose_name='پیشرفت هنگام درخواست')),
                ('status', models.CharField(choices=[('pending', 'در انتظار تایید کسب\u200cوکار'), ('approved', 'تایید و اعطا شده'), ('rejected', 'رد شده'), ('used', 'استفاده شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تایید')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ استفاده')),
                ('business_note', models.TextField(blank=True, null=True, verbose_name='یادداشت کسب\u200cوکار')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gift_claims', to='accounts.businessprofile', verbose_name='کسب\u200cوکار')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elite_gift_claims', to='accounts.customerprofile', verbose_name='مشتری')),
                ('elite_gift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='packages.elitegift', verbose_name='هدیه ویژه')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gift_claims', to='packages.package', verbose_name='پکیج')),
            ],
            options={
                'verbose_name': 'درخواست هدیه ویژه',
                'verbose_name_plural': 'درخواست\u200cهای هدیه ویژه',
                'ordering': ['-created_at'],
                'unique_together': {('customer', 'package')},
            },
        ),
    ]
