# Generated by Django 5.0.7 on 2025-11-10 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0004_elitegiftclaim'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='elitegiftclaim',
            unique_together=set(),
        ),
    ]
