# Generated by Django 5.0.7 on 2025-11-10 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0005_alter_elitegiftclaim_unique_together'),
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='elite_gift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='packages.elitegift', verbose_name='هدیه ویژه'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('regular', 'عادی'), ('elite_gift', 'هدیه ویژه')], default='regular', max_length=50, verbose_name='نوع تراکنش'),
        ),
    ]
